# 工作流名称
name: Sync-Images-to-DockerHub-Example
# 工作流运行时显示名称
run-name: ${{ github.actor }} is Sync Images to DockerHub.
# 怎样触发工作流
on:
  push:
    branches: [ "main","ks" ]
  pull_request:
    branches: [ "main","ks" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# 工作流程任务（通常含有一个或多个步骤）
jobs:
  syncimages:
    runs-on: ubuntu-latest
    environment: dev
    steps:
    - name: Checkout Repos
      uses: actions/checkout@v3
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2.9.1

    # - name: Login to Docker Hub
    #   uses: docker/login-action@v2.2.0
    #   with:
    #     username: ${{ secrets.DOCKER_USERNAME }}
    #     password: ${{ secrets.DOCKER_PASSWORD }}
    #     logout: false
        
    - name: Use Skopeo Tools Sync Image to Docker Hub
      run: |
        #!/usr/bin/env bash
        echo -e '[registries.insecure]\nregistries = ["hub.cloud.lingbohome.com"]' | sudo tee -a /etc/containers/registries.conf
        skopeo login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }} registry.cn-shanghai.aliyuncs.com
        skopeo copy  docker://gcr.io/distroless/static:nonroot docker://hub.cloud.lingbohome.com/distroless/static:nonroot
        # skopeo copy  docker://docker.io/paketobuildpacks/builder-jammy-base:0.4.321 docker://registry.cn-shanghai.aliyuncs.com/kube-shipper/paketo-cnb-builder-jammy-base:0.4.321
        # skopeo copy  docker://docker.io/paketobuildpacks/run-jammy-base:0.1.124 docker://registry.cn-shanghai.aliyuncs.com/kube-shipper/paketo-cnb-run-jammy-base:0.1.124
        # skopeo copy  docker://docker.io/paketobuildpacks/run-jammy-base:0.1.95 docker://registry.cn-shanghai.aliyuncs.com/kube-shipper/paketo-cnb-run-jammy-base:0.1.95
        # skopeo copy  docker://hub.cloud.lingbohome.com/kaniko-project/executor:v1.5.1 docker://registry.cn-shanghai.aliyuncs.com/kube-shipper/kaniko-project-executor:v1.5.1
        # skopeo copy  docker://hub.cloud.lingbohome.com/tekton-releases/github.com/tektoncd/pipeline/cmd/git-init:v0.40.2 docker://registry.cn-shanghai.aliyuncs.com/kube-shipper/tektoncd-pipeline-cmd-git-init:v0.40.2
        # skopeo copy  docker://hub.cloud.lingbohome.com/paketobuildpacks/builder-jammy-base:0.4.265 docker://registry.cn-shanghai.aliyuncs.com/kube-shipper/paketo-cnb-builder-jammy-base:0.4.265
        # skopeo copy  docker://docker.io/library/bash:5.1.4 docker://registry.cn-shanghai.aliyuncs.com/kube-shipper/bash:5.1.4
        # skopeo copy  docker://mcr.microsoft.com/powershell:nanoserver docker://registry.cn-shanghai.aliyuncs.com/kube-shipper/powershell:nanoserver
        # skopeo copy  docker://hub.cloud.lingbohome.com/gcr-sync/tektoncd-pipeline-controller:v0.54.2 docker://registry.cn-shanghai.aliyuncs.com/kube-shipper/tektoncd-pipeline-controller:v0.54.2
        # skopeo copy  docker://hub.cloud.lingbohome.com/gcr-sync/tektoncd-pipeline-entrypoint:v0.54.0 docker://registry.cn-shanghai.aliyuncs.com/kube-shipper/tektoncd-pipeline-entrypoint:v0.54.0
        # skopeo copy  docker://hub.cloud.lingbohome.com/gcr-sync/tektoncd-pipeline-nop:v0.54.0 docker://registry.cn-shanghai.aliyuncs.com/kube-shipper/tektoncd-pipeline-nop:v0.54.0
        # skopeo copy  docker://hub.cloud.lingbohome.com/gcr-sync/tektoncd-pipeline-workingdirinit:v0.54.0 docker://registry.cn-shanghai.aliyuncs.com/kube-shipper/tektoncd-pipeline-workingdirinit:v0.54.0
        # skopeo copy  docker://hub.cloud.lingbohome.com/cgr-sync/chainguard/busybox docker://registry.cn-shanghai.aliyuncs.com/kube-shipper/chainguard-busybox
        # skopeo copy  docker://hub.cloud.lingbohome.com/gcr-sync/tektoncd-pipeline-sidecarlogresults:v0.54.0 docker://registry.cn-shanghai.aliyuncs.com/kube-shipper/tektoncd-pipeline-sidecarlogresults:v0.54.0
        # skopeo copy  docker://hub.cloud.lingbohome.com/gcr-sync/tektoncd-pipeline-events:v0.54.0 docker://registry.cn-shanghai.aliyuncs.com/kube-shipper/tektoncd-pipeline-events:v0.54.0
        # skopeo copy  docker://hub.cloud.lingbohome.com/gcr-sync/tektoncd-pipeline-webhook:v0.54.0 docker://registry.cn-shanghai.aliyuncs.com/kube-shipper/tektoncd-pipeline-webhook:v0.54.0

        # skopeo copy  docker://docker.io/kubesphere/kubectl:v1.27.4 docker://registry.cn-shanghai.aliyuncs.com/kube-shipper/kubectl:v1.27.4   
        # skopeo copy  docker://docker.io/paketobuildpacks/run-jammy-base:0.1.94 docker://registry.cn-shanghai.aliyuncs.com/kube-shipper/paketo-cnb-run-jammy-base:0.1.94
        # skopeo copy  docker://kubesphere/helm:v3.12.1 docker://hub.cloud.lingbohome.com/kubesphere/helm:v3.12.1
        # skopeo copy  docker://gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/controller:v0.54.2 docker://hub.cloud.lingbohome.com/gcr-sync/tektoncd-pipeline-controller:v0.54.2
        # skopeo copy docker://gcr.io/kaniko-project/executor:v1.19.2 docker://hub.cloud.lingbohome.com/kaniko-project/executor:v1.19.2
        # skopeo copy docker://gcr.io/kaniko-project/executor:v1.9.2 docker://hub.cloud.lingbohome.com/kaniko-project/executor:v1.9.2
        # skopeo copy docker://gcr.io/kaniko-project/executor:v1.5.2 docker://hub.cloud.lingbohome.com/kaniko-project/executor:v1.5.2
        # skopeo copy docker://gcr.io/kaniko-project/executor:v1.9.1 docker://hub.cloud.lingbohome.com/kaniko-project/executor:v1.9.1
        # skopeo copy docker://gcr.io/kaniko-project/executor:v1.5.1 docker://hub.cloud.lingbohome.com/kaniko-project/executor:v1.5.1
        # skopeo copy docker://paketobuildpacks/builder-jammy-base:0.4.265  docker://hub.cloud.lingbohome.com/paketobuildpacks/builder-jammy-base:0.4.265
        # skopeo copy  docker://gcr.io/buildpacks/builder:v1 docker://hub.cloud.lingbohome.com/buildpacks/builder:v1
        # skopeo copy  docker://gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/git-init:v0.40.2 docker://hub.cloud.lingbohome.com/tekton-releases/github.com/tektoncd/pipeline/cmd/git-init:v0.40.2
        # skopeo copy  docker://gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/entrypoint:v0.54.0 docker://hub.cloud.lingbohome.com/gcr-sync/tektoncd-pipeline-entrypoint:v0.54.0
        # skopeo copy  docker://gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/nop:v0.54.0 docker://hub.cloud.lingbohome.com/gcr-sync/tektoncd-pipeline-nop:v0.54.0
        # skopeo copy  docker://gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/sidecarlogresults:v0.54.0 docker://hub.cloud.lingbohome.com/gcr-sync/tektoncd-pipeline-sidecarlogresults:v0.54.0
        # skopeo copy  docker://gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/workingdirinit:v0.54.0 docker://hub.cloud.lingbohome.com/gcr-sync/tektoncd-pipeline-workingdirinit:v0.54.0
        # skopeo copy  docker://cgr.dev/chainguard/busybox docker://hub.cloud.lingbohome.com/cgr-sync/chainguard/busybox
        # skopeo copy  docker://mcr.microsoft.com/powershell:nanoserver docker://hub.cloud.lingbohome.com/mcr-sync/powershell:nanoserver
        # skopeo copy docker://gcr.io/tekton-releases/github.com/tektoncd/dashboard/cmd/dashboard:v0.42.0 docker://hub.cloud.lingbohome.com/gcr-sync/tektoncd-dashboards-dashboard:v0.42.0
        # skopeo copy --all docker://gcr.io/tekton-releases/github.com/tektoncd/triggers/cmd/controller:v0.25.3 docker://hub.cloud.lingbohome.com/gcr-sync/tektoncd-triggers-controller:v0.25.3
        # skopeo copy --all docker://gcr.io/tekton-releases/github.com/tektoncd/triggers/cmd/webhook:v0.25.3 docker://hub.cloud.lingbohome.com/gcr-sync/tektoncd-triggers-webhook:v0.25.3
        # skopeo copy --all docker://gcr.io/tekton-releases/github.com/tektoncd/triggers/cmd/interceptors:v0.25.3 docker://hub.cloud.lingbohome.com/gcr-sync/tektoncd-triggers-interceptors:v0.25.3
        # skopeo copy --all docker://gcr.io/tekton-releases/github.com/tektoncd/triggers/cmd/eventlistenersink:v0.25.3 docker://hub.cloud.lingbohome.com/gcr-sync/tektoncd-triggers-eventlistenersink:v0.25.3
        # skopeo copy --all docker://gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/controller:v0.54.0 docker://hub.cloud.lingbohome.com/gcr-sync/tektoncd-pipeline-controller:v0.54.0
        # skopeo copy --all docker://gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/events:v0.54.0 docker://hub.cloud.lingbohome.com/gcr-sync/tektoncd-pipeline-events:v0.54.0
        # skopeo copy --all docker://gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/resolvers:v0.54.0 docker://hub.cloud.lingbohome.com/gcr-sync/tektoncd-pipeline-resolvers:v0.54.0
        # skopeo copy --all docker://gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/webhook:v0.54.0 docker://hub.cloud.lingbohome.com/gcr-sync/tektoncd-pipeline-webhook:v0.54.0
 
